apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-configuration
    secret:
      name: jenkins-secrets
  groovyScripts:
    configurations:
    - name: jenkins-configuration
    secret:
      name: jenkins-secrets
  master:
    plugins:
    - name: kubernetes-cli
      version: "1.9.0"
    - name: kubernetes-cd
      version: "2.3.1"
    #- name: blueocean
    #  version: "1.24.3"
    basePlugins:
    - name: kubernetes
      version: "1.27.3"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.4.5"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.45"
    - name: kubernetes-credentials-provider
      version: "0.15"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-jobs
    targets: "cicd/jobs/*.groovy"
    description: "Jenkins jobs"
    repositoryBranch: master
    repositoryUrl: https://github.com/adyb-fj-cns/jenkins-example-pipelines.git
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-operator-example-ui
spec:
  selector:
    app: jenkins-operator
  type: ClusterIP
  ports:
  - port: 8080





    