apiVersion: v1
kind: Secret
metadata:
  name:  grafana
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
    app: jenkins-operator
    jenkins-cr: example
    watch: "true"
  annotations:
    "jenkins.io/credentials-description": "Grafana Credentials"
stringData:
  username: admin
  password: password